[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/.netlify/functions/:name"
  to = "/.netlify/functions/:name"
  status = 200

[context.production]
  [context.production.environment]
    TC_CLIENT_ID = ""
    TC_CLIENT_SECRET = ""
